### ISSUE TITLE
Misc changes according to changes in models

### ISSUE THREAD

**Issue by MiklerGM** [chronhq/microservices#10]
- [x] Populate cached data with elements without location (#11)
- [x] Add url field for narratives (#9)
- [ ] Support negative dates for cities (https://github.com/chronhq/microservices/issues/10#issuecomment-464273862)
```
ValueError: time data '-801-01-01T00:00:00' does not match format '%Y-%m-%dT%H:%M:%S'
```

UPD:

- [x] Don't add cities, actors, ~~battles~~ without label (#11)
- [x] Fetch only valuable cities, like capitals (#11)

**Comment by quorth0n** [comment]
After writing an overcomplicated date parsing function I found that [django does not support BC dates](https://code.djangoproject.com/ticket/24955) despite postgres having some limited support. I propose we use "0001-01-01" for all negative dates for the time being.

**Comment by MiklerGM** [comment]
Ok, we have plenty of history to cover for ~2000 years, before that will become a real issue

Thanks
